version: '2.4'

services:

  prometheus:
    image: prom/prometheus:v2.33.4
    container_name: prometheus
    user: root
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /data/prometheus/:/prometheus/
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.config.file=/etc/prometheus/web.yml'
      - '--web.enable-lifecycle'
    links:
      - alertmanager:alertmanager
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
      - /data/alertmanager/:/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.config.file=/etc/alertmanager/web.yml'
    links:
      - prometheus-webhook-dingtalk:prometheus-webhook-dingtalk
    restart: always
  
  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./grafana/:/etc/grafana/
      - /data/grafana/:/var/lib/grafana/
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Your's Password
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: always

  prometheus-webhook-dingtalk:
    image: timonwong/prometheus-webhook-dingtalk
    container_name: prometheus-webhook-dingtalk
    ports:
      - 127.0.0.1:8060:8060
    volumes:
      - ./prometheus-webhook-dingtalk:/etc/prometheus-webhook-dingtalk/
    command:
      - '--config.file=/etc/prometheus-webhook-dingtalk/config.yml'
      - '--web.enable-lifecycle'
    restart: always
