# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    basic_auth:
      username: alertmanager username
      password: alertmanager password

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
  - "/etc/prometheus/rules/*.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']
    basic_auth:
      username: prometheus username
      password: prometheus password

  # node_exporter
  - job_name: node_exporter
    scrape_interval: 30s
    basic_auth:
      username: node_exporter username
      password: node_exporter password

    file_sd_configs:
    - refresh_interval: 1m
      files:
      - "/etc/prometheus/file_sd_config/*.yml"

  # https_exporter
  - job_name: https_exporter
    scrape_interval: 30s
    basic_auth:
      username: node_exporter username
      password: node_exporter password
    scheme: https
    tls_config:
      insecure_skip_verify: true
    http_sd_configs:
      - url: "https://example.com/api/node"
        refresh_interval: 60s



